# Generated by Django 3.0.3 on 2020-02-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Full Name')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('superuser', models.BooleanField(default=False, verbose_name='Is Super User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
